language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
    - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
    - composer install
    - cp data/config/aws.ini.orig data/config/aws.ini

script:
    - phpunit --coverage-text

after_script:
    - php bin/coveralls -v

notifications:
  email: false
